### Arrays

In [2]:
import numpy as np

In [6]:
mylist = [1,2,3]

In [7]:
type(mylist)

list

In [8]:
np.array(mylist)

array([1, 2, 3])

In [9]:
mylist   #it is not affected

[1, 2, 3]

In [10]:
myarr = np.array(mylist)

In [11]:
myarr

array([1, 2, 3])

In [12]:
type(myarr)

numpy.ndarray

In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)  #with step size

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.linspace(0,10,3)  #it gives 3 evenly spaced numbers between 0 to 10 both included

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [26]:
np.eye(5)   #it gives a identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5) 

array([0.20553202, 0.18001161, 0.29886749, 0.37212657, 0.22168301])

In [33]:
np.random.rand(5,4)

array([[0.10428736, 0.31811529, 0.09882343, 0.40170388],
       [0.84442386, 0.34848873, 0.73802578, 0.30282133],
       [0.62533596, 0.65756317, 0.24553782, 0.14324926],
       [0.72034702, 0.13958345, 0.45883071, 0.98406662],
       [0.66708916, 0.52770553, 0.26806565, 0.00486979]])

In [34]:
np.random.randn(10)

array([ 1.20984612, -0.09293789, -0.25334433, -0.08381868,  1.60326773,
       -0.50631511, -0.03902841, -1.24613642,  1.03813361, -0.06282696])

In [35]:
np.random.randn(2,3)

array([[ 1.52412193, -0.81314509,  1.17584885],
       [ 1.48996827, -0.87767331, -0.77154707]])

In [36]:
np.random.randint(0,101,5)

array([ 3, 32, 14, 96, 10])

In [37]:
np.random.randint(0,101,(4,5))

array([[88, 26, 29, 49, 87],
       [66, 27, 27, 37, 31],
       [84,  1, 24, 11, 30],
       [90, 86, 74,  8, 30]])

In [38]:
np.random.seed(42)   #to get same set of random numbers
np.random.rand(4)     #both should be in same cell

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
arr = np.arange(0,25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.reshape(5,5)   #5*5=25(total elements) so it will work

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
random_arr = np.random.randint(0,101,10)

In [43]:
random_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [44]:
random_arr.max()

99

In [49]:
random_arr.argmax()   #returns index of max element

5

In [47]:
random_arr.min()

2

In [48]:
random_arr.argmin()

7

In [50]:
random_arr.dtype   #returns data type holded by the array

dtype('int32')

In [51]:
random_arr.shape

(10,)

In [52]:
myarr = random_arr.reshape(5,2)

In [53]:
myarr.shape

(5, 2)

### Indexing and Selection

In [54]:
arr = np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[8]

8

In [57]:
arr[1:5]

array([1, 2, 3, 4])

In [58]:
arr[:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [60]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[0:5]= 100    #broadcasting operation

In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr = np.arange(0,11)

In [65]:
slice_of_array =  arr[0:5]

In [66]:
slice_of_array

array([0, 1, 2, 3, 4])

In [67]:
slice_of_array[:] = 99

In [68]:
slice_of_array

array([99, 99, 99, 99, 99])

In [69]:
arr   #it also changed as slice_of_array was pointing to arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [70]:
#in order to avoid this we need to create copy of original array and make changes to it
arr_copy = arr.copy()

In [71]:
arr_copy[:] = 100

In [72]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr  #now it remains unchanged

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [3]:
arr_2d = np.array([[1,5,55],[52,64,97],[69,878,45]])

In [4]:
arr_2d

array([[  1,   5,  55],
       [ 52,  64,  97],
       [ 69, 878,  45]])

In [5]:
arr_2d.shape

(3, 3)

In [6]:
arr_2d[0]

array([ 1,  5, 55])

In [7]:
arr_2d[2]

array([ 69, 878,  45])

In [9]:
arr_2d[1][1]

64

In [10]:
arr_2d[1,1]    #same output

64

In [11]:
arr_2d[0,2]

55

In [12]:
arr_2d[0:2,:]   #select rows from 0 to 1 and all the respective columns

array([[ 1,  5, 55],
       [52, 64, 97]])

In [13]:
arr_2d[:,:2]    #select all rows and respective column from 0 to 1

array([[  1,   5],
       [ 52,  64],
       [ 69, 878]])

In [15]:
arr_2d[1,:2]

array([52, 64])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [19]:
bool_array = arr>4

In [20]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [21]:
#we can filter original array
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
#their is an easy step to do that
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### Operations

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [26]:
arr + arr    #both array should be of same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [28]:
#numpy deals specially with division by zero
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr / arr

C:\Users\Nikhil\AppData\Local\Temp\ipykernel_24520\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [30]:
1/0

ZeroDivisionError: division by zero

In [31]:
1/arr

C:\Users\Nikhil\AppData\Local\Temp\ipykernel_24520\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [32]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [33]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [34]:
np.log(arr)

C:\Users\Nikhil\AppData\Local\Temp\ipykernel_24520\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr.sum()

55

In [37]:
arr.max()

10

In [38]:
arr.var()

10.0

In [39]:
arr.std()

3.1622776601683795

In [40]:
arr.mean()

5.0

In [42]:
arr = np.arange(0,25).reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.sum()

300

In [46]:
 arr.sum(axis= 0)      #columnwise summation 

array([50, 55, 60, 65, 70])

In [47]:
arr.sum(axis=1)       #rowwise summation

array([ 10,  35,  60,  85, 110])