In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
X = df.drop('sales',axis=1)

In [4]:
y = df['sales']

In [18]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [7]:
poly_features = polynomial_converter.fit_transform(X)

In [8]:
poly_features.shape

(200, 19)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(X_train)   #only fit on train data but transform test data as well

StandardScaler()

In [14]:
X_train = scaler.transform(X_train)

In [15]:
X_test = scaler.transform(X_test)

In [16]:
#just see the difference in the scaled data 
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [17]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

#### L2 Regularization  Ridge Regression

In [19]:
from sklearn.linear_model import Ridge

In [20]:
ridge_model = Ridge(alpha=10)

In [21]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [22]:
test_predictions = ridge_model.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [24]:
MAE = mean_absolute_error(y_test,test_predictions)

In [25]:
MAE

0.5774404204714175

In [26]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [27]:
RMSE

0.8946386461319671

In [28]:
#To get correct value of alpha we need to perform cross validation 

In [29]:
from sklearn.linear_model import RidgeCV

In [35]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_squared_error')
#Ridge regression with built-in cross-validation
#By default, it performs efficient Leave-One-Out Cross-Validation.
#alphas : Array of alpha values to try.default=(0.1, 1.0, 10.0)
#cv : Determines the cross-validation splitting strategy.(no. of folds)

In [36]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_squared_error')

In [37]:
ridge_cv_model.alpha_  #reports the alpha which performs the best

0.1

In [33]:
from sklearn.metrics import SCORERS

In [34]:
SCORERS.keys() #different types of errors

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig

In [38]:
test_predictions = ridge_cv_model.predict(X_test)

In [39]:
MAE = mean_absolute_error(y_test,test_predictions)

In [40]:
RMSE = mean_squared_error(y_test,test_predictions)**0.5

In [41]:
MAE

0.4273774884331876

In [42]:
RMSE

0.6180719926951581

In [43]:
#so i did find an better alpha value based on cross validation

In [44]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [45]:
ridge_cv_model.best_score_

-0.37770668487073655

#### L1 Regularization Lasso Regression

In [47]:
from sklearn.linear_model import LassoCV  #for Lasso we need to provide the alpha value

In [56]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5) 
#for LassoCV it takes the best alpha value using Cross validation

In [57]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [58]:
lasso_cv_model.alpha_

0.49430709092258285

In [59]:
test_predictions = lasso_cv_model.predict(X_test)

In [60]:
MAE = mean_absolute_error(y_test,test_predictions)

In [61]:
RMSE = mean_squared_error(y_test,test_predictions)**0.5

In [62]:
MAE

0.6541723161252856

In [63]:
RMSE

1.1308001022762535

In [64]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

##### L1 and L2 Regularization Elastic Net

In [19]:
from sklearn.linear_model import ElasticNetCV

In [20]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],eps=0.001,n_alphas=100,max_iter=100000)

In [21]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [22]:
elastic_model.l1_ratio_   #gives best ratio

1.0

In [23]:
elastic_model.alpha_

0.004943070909225827

In [24]:
elastic_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [25]:
test_prediction = elastic_model.predict(X_test)

In [29]:
MAE = mean_absolute_error(y_test,test_prediction)

In [30]:
MAE

0.4335034618590058